# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Путь к JDK 21 (требуется для Minecraft 1.21.4)
org.gradle.java.home=C:/Program Files/Java/jdk-21
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.14
# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=dev.client
archives_base_name=1.21.4
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.119.3+1.21.4
