package dev.client.api.nullcry.helper.other;

import java.util.List;

public class ModeratorSHIPUCHKA {

    public static final List<String> MODERATOR_NAMES = List.of(
            "cartem_pawlow", "yaBIG_PIG", "leon4ik1265", "M0Rell", "ItsLaMeNo228",
            "_XrABroStb_", "_Wasted_", "Rnzai101", "d3s1rr", "Xinero", "FuNtImEsosoezzz",
            "shift1K", "catwithcider", "ferdiguns", "elvawix", "pakucon", "Dangerwan", "AaseKasse",
            "kotwithcookie", "5ivkola", "qartem_pawlow", "qqlone", "yaPankYaLegenda",
            "killaura46", "HedRed2008", "sovipis213", "Kuratev", "DisNaLuk", "Xvostik333",
            "_PoJlToH_v_KeDaX", "GigabyteTop001", "stasikpid228", "Prepo_Tar", "DestroyeBoy",
            "ShulkerMe", "Sinex87", "catwithwine", "FrostyKKKKKKk", "_Holgan_", "Alisa_Lisna",
            "Stringers", "Shadow_Divine", "qwertyrrr", "bublikbesplatno", "teckstyra",
            "olegun", "Nesquik213", "hot_chick_", "nevepsycho", "Fen1x_b1b0", "Homechok",
            "Evgeny6780", "freylik", "axcu32", "1Viad", "Ecstacy_level", "216mypeek",
            "KotBac9", "Glebik_Viz", "lastocha_zxc", "_Clinkz_", "Noghtalit", "ckyka0_0",
            "stalin_vozhd", "hi1kz0", "ThunderShadow", "_4y4kek_", "Raudov_", "Laossium",
            "Da1mon_666", "DelsHearTache", "_Drase_", "WhiteMan4990", "shardov", "Bakkap",
            "MANDA_R1NKA", "Jeson", "rabai", "Tukich_bavalo", "NE_MANZARIUS", "faquesty",
            "itstik66", "leozart228", "_TBo9I_PaDoSTb", "MercyIzReal", "catwithbeer",
            "tequesty", "Black_Star_Girl", "Fr1znt", "Bayerfn", "TesTar1254", "Dinar1001",
            "Apollons", "YALAMA", "ArtCombo", "siinta", "BuHoBHuK__", "qveezer_", "Hadzaki",
            "Mavgr1758", "kiselb312123", "milkimas", "_Rape_seRies", "TheJustice",
            "Ya_He_power", "FacelessEgoist", "ThunderRoses", "_MoonM1ce_", "_Gesichtslos_",
            "Capitello", "DenekelYT", "Tinkers", "bone1nis", "FeelingHollow_", "ucTePuka",
            "Keldif", "Da1mon666", "Psycho_what", "1Valhalla", "DAHR2023",
            "xerinai", "merlin1601", "Wasted", "nikita200404", "Berasd_Master", "sienduk123",
            "UZI", "1WantToXyranaz", "hotchick", "krap1wka_ZXC", "pups", "_Bedmak_",
            "FatherlyLynx331", "apathyxdxdxdxd", "KLIKER_22", "Frostyqeaz", "FakeHappinessS",
            "bublikplatno", "KATYAN", "super_ne_chiter", "KreesTees", "krap1wka_zxc",
            "HepBbl_HoPM", "Iglobruh19", "Temniydar", "PopaBobra19", "zen1z", "hnazar1990",
            "HAHOL1", "fragizikXD", "FireDurgo", "validnumber",
            "vanya_batman2016", "_ixa", "dabackwooood", "mopwe", "dimon123511", "t0p_1gg",
            "Distr3", "BeeeId", "Wesd1x", "capibarich0", "Crazyb0mzik", "igroman9372",
            "Ded_Shahed131", "rkddi", "Demastir228", "molodoiparen", "tffhnmm",
            "deff4kk", "1WantToCherry", "Koni", "Wq1rtz", "Pro0zIt0cHa", "whitecatwithbeer",
            "3o4ka", "FlooMEXp", "underfeed", "lexa_chaynik", "0dnoklassniki",
            "Jada1553", "DanFordd", "lolyouPvP", "Kobra1337", "exhaustedy",
            "welsone", "Yukkich_", "MrYarikZOR", "_Alex_Gro_", "Shad3DaRK", "kittywithcookie",
            "stasananas338", "_IsusHristos_", "Razzle", "topstop1221", "Fr1dayyy", "Spotify",
            "Doomunos", "TheEzKv", "Ivk_A", "Artomchik_YT", "DELiti", "oxysensor",
            "DippeR_kz", "Calacrad", "1K0lchan1", "NightOfHeaven", "NonikStudioo", "1SARDO1",
            "nyashka228228", "KaPMA__", "tt4eknytuu", "mrkotia_pro", "sipwize", "ITZ_XIMIK",
            "SideAn07", "ethylecgonine", "Kr1zzl3X", "Nefolmi",
            "Aktassi", "al2k", "Ykajs", "HAHA_kill", "Bobrila", "Martin08",
            "Amiraldik", "7luCJIo0T9", "lakicot", "reyichka", "Mwx", "UpSerd", "480FPS_CKOPOCTb",
            "Remeis", "fesfdwqqq", "Odnoklassniki", "Pekkek55", "BLoF",
            "TheMonixxx", "3aBuCtHuk", "DalCanRan", "Dangerwun", "MEP3OCTb_", "Im_best_unlucki4",
            "Gabrielsim", "Elethava", "Baer5265", "666dopamine", "soft_еуе", "MrPikachu69",
            "vallerryyy", "Riflane", "YourSoPretty", "mone1nis",
            "LoonMice", "reichka", "MADKA_R1NKA", "SwifFox", "Merop",
            "S1riys_", "SoyGer", "clava01", "jeyzetiqqq", "kipochy", "MoonWolf2552",
            "ffago228", "Mondric", "ghostboy565", "chipepapa", "pikasso2",
            "TesTar1254", "Talm_SxI", "GAVAdima", "farwedgames", "puirogbespl", "modevol",
            "NonameAnime", "rnara1", "666Kaifoff", "TheToxicMoon", "Sindy", "5chrdk",
            "hot_babyshka", "thmnxxx", "deff4kLOX", "1I9", "CKOPOCTb1717"
    );
}